name: Build and test

on: [pull_request, push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.19.0
        
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'pnpm'
        
      - name: Install dependencies
        run: pnpm i

      - name: Build
        run: pnpm build

      - test: Test
        run: pnpm test
